// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: NewPasswordEmail.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const newPasswordEmail = `-- name: NewPasswordEmail :one
UPDATE users
SET email=$1,hashed_password=$2 
WHERE id=$3
RETURNING id,email,created_at,updated_at,is_chirpy_red
`

type NewPasswordEmailParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

type NewPasswordEmailRow struct {
	ID          uuid.UUID
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsChirpyRed bool
}

func (q *Queries) NewPasswordEmail(ctx context.Context, arg NewPasswordEmailParams) (NewPasswordEmailRow, error) {
	row := q.db.QueryRowContext(ctx, newPasswordEmail, arg.Email, arg.HashedPassword, arg.ID)
	var i NewPasswordEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsChirpyRed,
	)
	return i, err
}
