// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: RevokeRefreshToken.sql

package database

import (
	"context"
)

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at=NOW(), updated_at=NOW()
WHERE token=$1
RETURNING token
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, token)
	err := row.Scan(&token)
	return token, err
}
