// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: UpgradeChirpyRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeChirpyRed = `-- name: UpgradeChirpyRed :one
UPDATE users
SET is_chirpy_red=TRUE
WHERE id=$1
RETURNING is_chirpy_red
`

func (q *Queries) UpgradeChirpyRed(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, upgradeChirpyRed, id)
	var is_chirpy_red bool
	err := row.Scan(&is_chirpy_red)
	return is_chirpy_red, err
}
